### ISSUE TITLE
Kunne "fryse" et subnett 

### ISSUE THREAD

**Issue by oyvindhagberg** [usit-gd/mreg#13]
Det har kommet ønske fra nettdrift og BSD om å kunne markere et subnett som "fryst" i tilfeller der man har planlagt å legge det ned og ikke ønsker at folk skal registrere flere nye maskiner på det.
I praksis vil det si at vi legger til et boolean-felt i subnett-tabellen som angir om subnettet er fryst, og hvis det er det så skal visse operasjoner (f.eks. legge til en host på det subnettet) kreve høyere tilgangsnivå enn det vanligvis gjør.

**Comment by nicolactic** [comment]
CLI sjekker 'frozen' til det gitte subnettet i host add
