### ISSUE TITLE
CRUD operations for /ipaddresses

### ISSUE THREAD

**Issue by MHmorgan** [usit-gd/mreg#19]
kunne legge til ressurser til en host ved en post request.

F.eks. for å legge til en ny ip addresse, 123.456.6.7, til hosten ulrik:  
url: `/hosts/ulrik.uio.no/ipaddress`
body: 
 ```
{
    "ipaddress": "123.456.6.7",
    "macaddress": null,
}
```

**Comment by nlhiorth** [comment]
Dette gjelder for POST

**Comment by geirtul** [comment]
Strukturen endres slik at ip adresser som ressurs er tilgjengelig fra /api/ipaddresses.
Å legge en IP til en host gjøres da ved POST til /ipaddresses, der hostname er påkrevd (ForeignKey)
