### ISSUE TITLE
SSHFP support

### ISSUE THREAD

**Issue by oyvindkolbu** [usit-gd/mreg#274]
Implement support for https://tools.ietf.org/html/rfc6594, and also Ed25519 from https://tools.ietf.org/html/rfc7479

[ ] - Create model, validator, serializer and view
[ ] - Add tests for various types of sshfp entries
[ ] - Add sshfp to zonefile export

**Comment by dmykarp** [comment]
[X ] - Create model, validator, serializer and view
[ ] - Add tests for various types of sshfp entries
[ ] - Add sshfp to zonefile export

**Comment by dmykarp** [comment]
[X] - Create model, validator, serializer and view
[ ] - Add tests for various types of sshfp entries
[X] - Add sshfp to zonefile export

**Comment by dmykarp** [comment]
https://github.com/usit-gd/mreg/pull/278

**Comment by dmykarp** [comment]
[X] - Create model, validator, serializer and view
[X] - Add tests for various types of sshfp entries
[X] - Add sshfp to zonefile export

**Comment by dmykarp** [comment]
PR is merged, the branch is deleted. I'm going to close the issue.
