### ISSUE TITLE
"<HostGroup: testgroup>" needs to have a value for field "id" before this many-to-many relationship can be used.

### ISSUE THREAD

**Issue by safeaim** [usit-gd/mreg#276]
https://github.com/usit-gd/mreg/blob/ca9350e6054fea8a877ecb607e30ca6cce02eaa6/mreg/api/v1/serializers.py#L274

Hvis denne linjen innholder "parent"-feltet:
` fields = ('hostgroup_name','parent') `
Så får man følgende feilmelding når man prøver å legge til en ny gruppe:

Request Method: | POST
-- | --
http://localhost:8000/hostgroups/
2.1.7
ValueError
"<HostGroup:testgroup>" needs to have a value for field "id" before this many-to-many relationship can be used.
/Users/myuser/git/mreg/venv/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py in __init__, line 823
/Users/myuser/git/mreg/venv/bin/python
3.7.2
['/Users/myuser/git/mreg',  '/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',  '/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7',  '/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',  '/Users/myuser/git/mreg/venv/lib/python3.7/site-packages']
Mon, 11 Mar 2019 23:34:17 +0100

Er løsningen at man implementerer en egen måte å lagre objektet på så lenge man har et many2many-field?

**Comment by oyvindkolbu** [comment]
Fixed in branch. Wrong usage of serializer.
