### ISSUE TITLE
Testmiljø på uio-maskin

### ISSUE THREAD

**Issue by oyvindhagberg** [usit-gd/mreg#63]
Få testmiljøet opp og kjøre, med server + cli installert på testmaskinen, så folk kan logge inn og teste ting uten å måtte installere noe selv.

**Comment by oyvindkolbu** [comment]
Bestilt test-database på postgres-hotellet.

**Comment by oyvindkolbu** [comment]
Oppe og går på mreg-test01 nå. Sendt en epost til mreg-utv med info.
