### ISSUE TITLE
Postmaster

### ISSUE THREAD

**Issue by oyvindhagberg** [usit-gd/mreg#71]
- Odberg skrev til postmaster i sommer, ifm sommerprosjektet.
  Fikk svar av Ingar Vindenes i epost 7.august, kopi til mreg-utv-listen.
- Ingar sa (kort oppsummert):
  - Det høres fornuftig ut med et standard MX-sett for hver sone med 
    mulighet for overstyring og at MX-settene vil være relativt statiske.
  - Det bør vurderes om SPF-oppføringer (TXT) skal bundles med MX,
    ift kompleksitet.

**Comment by oyvindkolbu** [comment]
Det vil vel kun være SPF for hostname som skal brukes som epostdomener, gir jo ingen mening med det for alle hoster. Per i dag har alle hoster MX, men trenger jo strengt tatt ikke (lengre). Bør ta en prat om man skal gå for kun MX for epostdomener.

**Comment by oyvindkolbu** [comment]
Siste kommentarer er at vi dropper MXset, men skal lage noe automatikk for å sette en TXT med  "v=spf1 -all" for alle hoster.
